<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '呼叫',
    'icon' => 'fa fa-fw fa-tel-bag',
    'url_type' => 'module_admin',
    'url_value' => 'call/home/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 8,
    'status' => 1,
    'child' => [
      [
        'title' => '首页',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => 'call/home/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [

        ]
      ],
      [
        'title' => '公告管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '公告列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/adv/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '客户管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '客户列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '导入客户',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/export',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '项目配置',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/project',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '项目描述',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/pjslist',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '项目列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/pjlist',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '分配管理',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/alloc',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '任务列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/task',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '公海列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/trash',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '回收列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/gtback',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '回收配置',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/backst',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '话术列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/custom/speechcraft',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '提醒管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '提醒列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/notice/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '提醒配置',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/notice/st',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '订单管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '订单列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/order/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '回款列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/order/return',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '员工管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '员工列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/employ/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '预约管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '待回访',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/ondate/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
            [
                'title' => '已回访',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/ondate/histroy',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '报表管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '报表列表(test)',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/report/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '统计管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '统计列表(test)',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/count/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '配置管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '参数配置',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/setting/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      [
        'title' => '授权管理',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
            [
                'title' => '授权列表',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'call/auth/index',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 100,
                'status' => 1,
            ],
        ]
      ],
      
    ],
  ],
];
