<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '商城',
    'icon' => 'fa fa-fw fa-shopping-bag',
    'url_type' => 'module_admin',
    'url_value' => 'shop/item/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 8,
    'status' => 1,
    'child' => [
      [
        'title' => '商品列表',
        'icon' => 'fa fa-fw fa-list',
        'url_type' => 'module_admin',
        'url_value' => 'shop/item/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '下架',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/item/disable',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '编辑',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/item/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '删除',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/item/delete',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '添加',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/item/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '上架',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/item/enable',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '分类管理',
        'icon' => 'fa fa-fw fa-play',
        'url_type' => 'module_admin',
        'url_value' => 'shop/cat/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '分类列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/cat/index',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '编辑',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/cat/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '添加',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/cat/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '品牌管理',
        'icon' => 'fa fa-fw fa-play',
        'url_type' => 'module_admin',
        'url_value' => 'shop/brand/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '品牌列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/brand/index',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '编辑',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/brand/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '添加',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/brand/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '属性管理',
        'icon' => 'fa fa-fw fa-play',
        'url_type' => 'module_admin',
        'url_value' => 'shop/props/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '属性列表',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/props/index',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '编辑',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/props/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '添加',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'shop/props/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
    ],
  ],
];
